const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257,
  },
  events: [
    {
      created: 1591604579000,
      duration: 7200000,
      id: '271158441',
      name: 'Rust Remote #3',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1598378400000,
      local_date: '2020-08-25',
      local_time: '20:00',
      updated: 1592460378000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 19,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: '',
      },
      is_online_event: true,
      group: {
        created: 1431526364000,
        name: 'Rust Munich',
        id: 18594917,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'rust-munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/rust-munich/events/271158441/',
      description: 'Third round of a purely online/remote meetup ',
      how_to_find_us: 'https://youtu.be/on4Tb0Ssdro',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1591080822000,
      duration: 7200000,
      id: '271028964',
      name: 'ONLINE-EVENT: Analyse von Anomalien in Watson Studio: Vorgehensweise und Tools',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593073800000,
      local_date: '2020-06-25',
      local_time: '10:30',
      updated: 1591081889000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 21,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: true,
        country: '',
        localized_country_name: '',
      },
      is_online_event: true,
      group: {
        created: 1400181332000,
        name: 'Data, Cloud and AI in Munich',
        id: 14476282,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Big-Data-Developers-in-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/271028964/',
      description: '<p>Sprecher:<br/>Matthias Biniok, Leader MVP Team DACH, Leader Space Tech Division DACH, Tech Sales AI Apps</p> <p>Leonard Brucksch, Technical Sales Data Science &amp; AI, Space Tech Division DACH</p> <p>Abstract: Das IBM Watson Studio bietet eine übergreifende Data Science &amp; Management Plattform mit unterschiedlichen Data Science Werkzeugen für verschiedene IT-Umgebungen (public Cloud, private Cloud und Desktop). Mit dem IBM Watson Studio können Sie mit mehreren Personen kollaborativ, übersichtlich, schnell und sicher an ihren Data Science Projekten arbeiten. Das IBM Watson Studio vereint dabei Werkzeuge für eine sehr schnelle und einfache Entwicklung und Bereitstellung von Modellen bis hin zu Werkzeugen, um komplexere Modelle zu erstellen. In der Präsentation wird anhand eines Anwendungsfalls zur Analyse und Auswertung von Anomalien diese Bandbreite an Funktionen und Werkzeugen des IBM Watson Studios in einer Live Demo vorgestellt. Mit der Data Refinery werden Daten aufbereitet, mithilfe von AutoAI, SPSS Modeler und Notebooks werden Modelle und Funktionen erstellt und via Watson Machine Learning bereitgestellt. Außerdem wird Event Streams &amp; Streams genutzt, um live Vorhersagen zu treffen. Zuletzt soll ein Dashboard generiert werden, dass die Daten visualisiert.</p> <p>Wir freuen uns auf euch und auf einen spannenden Austausch!</p> <p>Teilnahme:<br/>Die Teilnahme erfolgt ausschließlich online via WebEx. Eine separate Anmeldung ist nicht notwendig. Du kannst dich über folgenden Link ab 10.30 Uhr einwählen: https://ibm.webex.com/meet/schneider</p> <p>FAQs:<br/>Wie kann ich den Organisator kontaktieren, wenn ich Fragen habe?<br/>Du kannst mich gerne direkt über meine Mailadresse [masked] kontaktieren.</p> <p>In welcher Sprache wird die Roundtable durchgeführt?<br/>Die Roundtable wird in deutscher Sprache abgehalten.</p> ',
      how_to_find_us: 'https://ibm.webex.com/meet/schneider',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1591371902000,
      duration: 5400000,
      id: '271103883',
      name: 'Zarah Bruhn (Co-Founder of Social-Bee and Bring & Ring I Ashoka Fellow I Capital',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593532800000,
      local_date: '2020-06-30',
      local_time: '18:00',
      updated: 1591686001000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1392782924000,
        name: 'Startup Grind Munich',
        id: 12957402,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Startup-Grind-Munich',
        who: 'Entrepreneurs',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Startup-Grind-Munich/events/271103883/',
      description: 'To assume social responsibility with an entrepreneurial spirit for a diverse and colourful society in which everyone gets a chance This is Social Bee\'s great vision. After several internships and jobs in the fields of venture capital and start-ups, Zarah Bruhn founded the social start- up „Social-Bee“ together with her partner Maximilian Felsner in Munich. Germany’s first integration service provider uses the temporary employment model to integrate refugees into the labour market and society: Social-Bee takes care of all the bureaucratic work and supports its employees by offering them an opportunity to acquire further qualifications and participate in integration programs. After founding Social-Bee during the refugee-crisis, the current corona-pandemic has led her to co-found bringandring a platform to provide shopping assistance across Europe to minimise social contact and fight the spread of the virus.',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1590650306000,
      duration: 7200000,
      id: '270924096',
      name: 'Kotlin Meetup - June Edition',
      rsvp_limit: 120,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593018000000,
      local_date: '2020-06-24',
      local_time: '19:00',
      updated: 1590650306000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 67,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: true,
        country: '',
        localized_country_name: '',
      },
      is_online_event: true,
      group: {
        created: 1421043158000,
        name: 'Kotlin User Group Munich - KUG Munich',
        id: 18325305,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Kotlin-User-Group-Munich',
        who: 'KUG-Hacker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Kotlin-User-Group-Munich/events/270924096/',
      description: '<p>Hello Kotliners! Join us on our upcoming June meetup. We will be speaking with Raul Raja, CEO of 47Degree; Nick Skelton, Freelaner and Firebase GDE and Enrique López-Mañas.</p> <p>This event will be conducted online. We will let you know timewise the link for the online room.</p> <p>Agenda: TBD</p> <p>Have you been working on a project with Kotlin? Is there a library you would like to discuss? Would you like to try public speaking or need help to prepare a talk? Message us, come and have fun sharing your Kotlin story!</p> <p>Would you or your company like to host our meetup, please let us know!</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },

  ]
};

export { mockEvents };